services:
  - type: web
    name: myblog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn blog.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: blog.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: myblog-db
          property: connectionString

databases:
  - name: myblog-db
    plan: free
