# Generated by Django 4.2.21 on 2025-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cultureimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='culture_audio/'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cultures_images/'),
        ),
    ]
