# Generated by Django 4.2.21 on 2025-05-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
