# Generated by Django 4.2.21 on 2025-05-27 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_gastronomie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastronomie',
            name='date',
        ),
    ]
