# Generated by Django 4.2.21 on 2025-05-27 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_gastronomie_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastronomie',
            name='lieu',
        ),
        migrations.AddField(
            model_name='gastronomie',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
