# Generated by Django 4.2.21 on 2025-05-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_gastronomie_lieu_gastronomie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastronomie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
