# Generated by Django 4.2.21 on 2025-05-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_gastronomie_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gastronomie',
        ),
    ]
