# Generated by Django 4.2.21 on 2025-05-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_gastronomie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastronomie',
            old_name='content',
            new_name='description',
        ),
    ]
