# Generated by Django 4.2.21 on 2025-05-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_villepatrimoine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conseilvoyage',
            options={'ordering': ['-date'], 'verbose_name': 'Conseil de voyage', 'verbose_name_plural': 'Conseils de voyage'},
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='lieu',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='agenda',
            old_name='titre',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='conseilvoyage',
            old_name='date_publication',
            new_name='date',
        ),
        migrations.AddField(
            model_name='conseilvoyage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
