# Generated by Django 4.2.21 on 2025-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_conseilvoyage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'ordering': ['titre'], 'verbose_name': "ville d'abidjan", 'verbose_name_plural': 'Destinations abidjan'},
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='date_publiée',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='ville',
            new_name='titre',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agenda_images/'),
        ),
    ]
