# Generated by Django 4.2.21 on 2025-05-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_destinations_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture',
            old_name='titre',
            new_name='title',
        ),
    ]
