# Generated by Django 4.2.21 on 2025-05-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_titre_culture_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='culture',
            old_name='contenu',
            new_name='content',
        ),
    ]
