# Generated by Django 4.2.21 on 2025-05-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_contenu_culture_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conseilvoyage',
            old_name='contenu',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='conseilvoyage',
            old_name='titre',
            new_name='title',
        ),
    ]
