# Generated by Django 4.2.21 on 2025-05-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_contenu_conseilvoyage_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'ordering': ['title'], 'verbose_name': "ville d'abidjan", 'verbose_name_plural': 'Destinations abidjan'},
        ),
        migrations.RenameField(
            model_name='destinations',
            old_name='titre',
            new_name='title',
        ),
    ]
