# Generated by Django 4.2.21 on 2025-05-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_contenu_apropos_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villepatrimoine',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='villepatrimoine',
            old_name='date_pub',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='villepatrimoine',
            old_name='titre',
            new_name='title',
        ),
    ]
