# Generated by Django 4.2.21 on 2025-06-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_description_villepatrimoine_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('categorie', models.CharField(choices=[('luxe', 'Hôtel de luxe'), ('moyen', 'Hôtel milieu de game'), ('location', 'Location de vacances'), ('atypique', 'Hébergement atypique')], max_length=20)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('prix_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hebergements/')),
                ('site_web', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
