# Generated by Django 4.2.21 on 2025-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_hebergement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('categorie', models.CharField(choices=[('gastro', 'Gastronomie'), ('rapide', 'Restauration rapide'), ('local', 'Cuisine locale'), ('cafes', 'Café & Boulangeries')], max_length=20)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('site_web', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
