# Generated by Django 4.2.21 on 2025-06-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPratique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Ex: 📍, 🛂, 💱', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(help_text='Utilise des listes en HTML, ex: <ul><li>...</li></ul>')),
            ],
        ),
    ]
