# Generated by Django 4.2.21 on 2025-06-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_categorieactivite_activite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorieactivite',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
