# Generated by Django 4.2.21 on 2025-06-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_categorieactivite_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='date_debut_texte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
