# Generated by Django 4.2.21 on 2025-06-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_carouselslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselSlide',
        ),
    ]
