# Generated by Django 4.2.21 on 2025-06-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='est_recommande',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categorie',
            field=models.CharField(choices=[('resto', 'Restaurant'), ('rapide', 'Restauration rapide'), ('local', 'Cuisine locale'), ('maquis', 'Maquis'), ('cafes', 'Café & Boulangeries')], max_length=20),
        ),
    ]
