# Generated by Django 4.2.21 on 2025-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_restaurant_est_recommande_alter_restaurant_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatTypique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
            ],
        ),
    ]
