# Generated by Django 4.2.21 on 2025-06-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
