# Generated by Django 4.2.21 on 2025-06-24 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_restaurant_horaires_restaurant_prix_moyen_plat'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='popularite',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='prix_moyen',
            field=models.CharField(blank=True, choices=[('bas', 'Moins de 3 000 FCFA'), ('moyen', 'Entre 3 000 et 7 000 FCFA'), ('haut', 'Plus de 7 000 FCFA')], max_length=50, null=True),
        ),
    ]
