# Generated by Django 4.2.21 on 2025-06-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_restaurant_date_ajout_restaurant_popularite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='est_en_avant',
            field=models.BooleanField(default=False, help_text="Cochez pour l'événement du mois"),
        ),
    ]
