# Generated by Django 4.2.21 on 2025-06-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_culture_est_en_avant'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='categorie',
            field=models.CharField(choices=[('fetes', 'Fêtes'), ('cuisine', 'Cuisine'), ('artisanat', 'Artisanat')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
