# Generated by Django 4.2.21 on 2025-06-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_culture_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='culture',
            name='categorie',
            field=models.ForeignKey(choices=[('fetes', 'Fêtes'), ('cuisine', 'Cuisine'), ('artisanat', 'Artisanat')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='culture', to='app.categorieculture'),
        ),
    ]
