# Generated by Django 4.2.21 on 2025-06-24 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_categorieculture_alter_culture_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='culture', to='app.categorieculture'),
        ),
    ]
