# Generated by Django 4.2.21 on 2025-06-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_category_galleryimage_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie culturelle', 'verbose_name_plural': 'Catégories culturelles'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Image de galerie culture', 'verbose_name_plural': 'Images de galerie cultures'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Culture Sub_Catégorie', 'verbose_name_plural': 'Cultures Sub_Catégories'},
        ),
    ]
