# Generated by Django 4.2.21 on 2025-06-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_alter_category_image_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CulturalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topics/')),
                ('history', models.TextField()),
                ('meaning', models.TextField()),
                ('calendar', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='app.destinations')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='topic_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.culturaltopic')),
            ],
        ),
    ]
