# Generated by Django 4.2.21 on 2025-06-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_subcategory_is_featured_culturaltopic_culturalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lieux/')),
                ('localisation', models.CharField(max_length=255)),
                ('distance_km', models.FloatField()),
                ('duree', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('nature', 'Nature'), ('culture', 'Culture'), ('plage', 'Plage'), ('gastronomie', 'Gastronomie')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='culturaltopic',
            name='destination',
        ),
        migrations.DeleteModel(
            name='CulturalImage',
        ),
        migrations.DeleteModel(
            name='CulturalTopic',
        ),
    ]
