# Generated by Django 4.2.21 on 2025-06-25 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_lieu_remove_culturaltopic_destination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieu',
            options={'verbose_name': 'Autour de Babi', 'verbose_name_plural': 'Autour de Babis'},
        ),
    ]
