# Generated by Django 4.2.21 on 2025-06-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_lieu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='weekend_spot',
            field=models.BooleanField(default=False, verbose_name='Idée de sortie du week-end'),
        ),
    ]
