# Generated by Django 4.2.21 on 2025-06-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_lieu_weekend_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='type',
            field=models.CharField(choices=[('nature', 'Nature'), ('culture', 'Culture'), ('plage', 'Plage'), ('gastronomie', 'Gastronomie'), ('village', 'Village')], max_length=100),
        ),
    ]
