# Generated by Django 4.2.21 on 2025-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_lieu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='acces',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='equipement_conseille',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='niveau_difficulte',
            field=models.CharField(blank=True, choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='saison_ideale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='type',
            field=models.CharField(choices=[('nature', 'Nature'), ('culture', 'Culture'), ('plage', 'Plage'), ('gastronomie', 'Gastronomie'), ('village', 'Village'), ('randonnee', 'Randonnee'), ('animaux', 'Animaux')], max_length=100),
        ),
    ]
