# Generated by Django 4.2.21 on 2025-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_lieu_date_evenement_alter_lieu_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='type',
            field=models.CharField(choices=[('nature', 'Nature'), ('culture', 'Culture'), ('plage', 'Plage'), ('gastronomie', 'Gastronomie'), ('village', 'Village'), ('randonnee', 'Randonnee'), ('animaux', 'Animaux')], max_length=100),
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='sorties/')),
                ('type', models.CharField(choices=[('bar', 'Bar'), ('club', 'Club'), ('concert', 'Concert'), ('spectacle', 'Spectacle'), ('evenement', 'Événement')], max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('acces', models.CharField(blank=True, max_length=255, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('horaire', models.CharField(blank=True, max_length=100, null=True)),
                ('age_minimum', models.PositiveIntegerField(blank=True, null=True)),
                ('tarif', models.CharField(blank=True, max_length=100, null=True)),
                ('dress_code', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tendance', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, to='app.tag')),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
            },
        ),
    ]
