# Generated by Django 4.2.21 on 2025-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_lieu_type_sortie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortie',
            name='tags',
        ),
        migrations.AddField(
            model_name='sortie',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='programme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='tarif_moyen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
