# Generated by Django 4.2.21 on 2025-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_remove_sortie_tags_sortie_facebook_sortie_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='accessibilite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='age_minimum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='horaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='tarif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='type',
            field=models.CharField(choices=[('nature', 'Nature'), ('culture', 'Culture'), ('plage', 'Plage'), ('gastronomie', 'Gastronomie'), ('village', 'Village'), ('randonnee', 'Randonnee'), ('animaux', 'Animaux'), ('village', 'Village'), ('parc', 'Parc'), ('sport', 'Activité sportive'), ('centre_loisir', 'Centre de loisirs'), ('jeux', 'Jeux pour enfants')], max_length=100),
        ),
    ]
