# Generated by Django 4.2.21 on 2025-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_lieu_accessibilite_lieu_age_minimum_lieu_horaire_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteLoisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='loisirs/')),
                ('categorie', models.CharField(choices=[('parc', 'Parc'), ('sport', 'Activité sportive'), ('centre_loisir', 'Centre de loisirs'), ('jeux', 'Jeux pour enfants'), ('autre', 'Autre')], max_length=50)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('horaire', models.CharField(blank=True, max_length=255, null=True)),
                ('tarif', models.CharField(blank=True, max_length=100, null=True)),
                ('age_minimum', models.PositiveIntegerField(blank=True, null=True)),
                ('accessibilite', models.TextField(blank=True, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activité de loisir',
                'verbose_name_plural': 'Activités de loisir',
            },
        ),
    ]
