# Generated by Django 4.2.21 on 2025-06-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_activiteloisir'),
    ]

    operations = [
        migrations.CreateModel(
            name='LieuShopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='shopping/')),
                ('type', models.CharField(choices=[('marche', 'Marché local'), ('boutique', 'Boutique artisanale'), ('mall', 'Centre commercial'), ('concept_store', 'Concept Store'), ('autre', 'Autre')], max_length=50)),
                ('adresse', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lieu de shopping',
                'verbose_name_plural': 'Lieux de shopping',
            },
        ),
    ]
