# Generated by Django 4.2.21 on 2025-06-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_lieushopping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConseilVoyage',
        ),
    ]
