# Generated by Django 4.2.21 on 2025-06-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_delete_conseilvoyage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('bus', 'Bus / Car'), ('bateau', 'Bateau'), ('avion', 'Avion'), ('taxi', 'Taxi / VTC'), ('location', 'Location de voiture')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='transports/')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('horaires', models.CharField(blank=True, max_length=255, null=True)),
                ('tarifs', models.CharField(blank=True, max_length=255, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Moyen de transport',
                'verbose_name_plural': 'Transports',
            },
        ),
        migrations.RemoveField(
            model_name='activite',
            name='categorie',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='Gastronomie',
        ),
        migrations.RemoveField(
            model_name='imagesupplementaire',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='plat',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='PlatTypique',
        ),
        migrations.DeleteModel(
            name='VillePatrimoine',
        ),
        migrations.DeleteModel(
            name='Activite',
        ),
        migrations.DeleteModel(
            name='CategorieActivite',
        ),
        migrations.DeleteModel(
            name='Destinations',
        ),
        migrations.DeleteModel(
            name='ImageSupplementaire',
        ),
        migrations.DeleteModel(
            name='Plat',
        ),
    ]
