# Generated by Django 4.2.21 on 2025-06-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_moyentransport_remove_activite_categorie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant/où manger', 'verbose_name_plural': 'Restaurants/où manger'},
        ),
        migrations.RenameField(
            model_name='lieushopping',
            old_name='horaires',
            new_name='heure_ouverture',
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='accessibility',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='services',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
    ]
