# Generated by Django 4.2.21 on 2025-06-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieushopping',
            name='conseil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
