# Generated by Django 4.2.21 on 2025-07-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_lieushopping_conseil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hebergement',
            name='prix_min',
        ),
        migrations.AddField(
            model_name='hebergement',
            name='accessibility',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='conseil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='heure_ouverture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='services',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='tarif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
