# Generated by Django 4.2.21 on 2025-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_subcategory_accessibility_subcategory_activite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='duree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
