# Generated by Django 4.2.21 on 2025-07-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_alter_lieu_distance_km_alter_lieu_duree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='acces',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='lieu',
            old_name='localisation',
            new_name='conseil',
        ),
        migrations.RemoveField(
            model_name='lieu',
            name='accessibilite',
        ),
        migrations.AddField(
            model_name='lieu',
            name='accessibility',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='activite',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lieu',
            name='quartier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='services',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
