# Generated by Django 4.2.21 on 2025-07-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0075_moyentransport_conseil_moyentransport_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='conseil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='specialite',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categorie',
            field=models.CharField(choices=[('resto', 'Restaurant'), ('rapide', 'Restauration rapide'), ('local', 'Cuisine locale'), ('maquis', 'Maquis'), ('rooftop', 'Rooftop'), ('cafes', 'Café & Boulangeries')], max_length=20),
        ),
    ]
