# Generated by Django 4.2.21 on 2025-07-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_activiteloisir_activite_proposee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebergement',
            name='adresse_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='adresse_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
