# Generated by Django 4.2.21 on 2025-07-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_hebergement_adresse_en_hebergement_adresse_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteloisir',
            name='accessibilite_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activiteloisir',
            name='accessibilite_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activiteloisir',
            name='activite_proposee_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activiteloisir',
            name='activite_proposee_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activiteloisir',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activiteloisir',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='activiteloisir',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activiteloisir',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apropos',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='accessibility_en',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='accessibility_fr',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='conseil_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='conseil_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='services_en',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='hebergement',
            name='services_fr',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='infopratique',
            name='content_en',
            field=models.TextField(help_text='Utilise des listes en HTML, ex: <ul><li>...</li></ul>', null=True),
        ),
        migrations.AddField(
            model_name='infopratique',
            name='content_fr',
            field=models.TextField(help_text='Utilise des listes en HTML, ex: <ul><li>...</li></ul>', null=True),
        ),
        migrations.AddField(
            model_name='infopratique',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='infopratique',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='accessibility_en',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='accessibility_fr',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='adresse_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='adresse_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='conseil_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='conseil_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='services_en',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='services_fr',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='accessibility_en',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='accessibility_fr',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='adresse_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='adresse_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='conseil_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='conseil_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='region_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='region_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='services_en',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='lieushopping',
            name='services_fr',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='conseil_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='conseil_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='horaires_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='horaires_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='services_en',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='services_fr',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='tarifs_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='tarifs_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='zone_desservi_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='moyentransport',
            name='zone_desservi_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fr',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='adresse_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='adresse_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='conseil_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='conseil_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='content_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='specialite_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='specialite_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='acces_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='acces_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='dress_code_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='dress_code_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='programme_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortie',
            name='programme_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='accessibility_en',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='accessibility_fr',
            field=models.CharField(blank=True, help_text='Infos transport et accessibilité', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='activite_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='activite_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='adresse_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='adresse_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='conseil_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='conseil_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='horaire_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='horaire_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='services_en',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='services_fr',
            field=models.TextField(blank=True, help_text='Services et équipements disponibles', null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
