# Generated by Django 4.2.21 on 2025-07-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_activiteloisir_accessibilite_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieushopping',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='lieushopping',
            name='nom_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='lieushopping',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='lieushopping',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
