# Generated by Django 4.2.21 on 2025-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conseil de voyage',
                'verbose_name_plural': 'Conseils de voyage',
                'ordering': ['-date_publication'],
            },
        ),
    ]
