# Generated by Django 4.2.21 on 2025-05-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinatoins',
            options={'ordering': ['ville'], 'verbose_name': 'ville en CI', 'verbose_name_plural': 'Destinations en CI'},
        ),
        migrations.AddField(
            model_name='destinatoins',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinatoins',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destinatoins',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
