# Generated by Django 4.2.21 on 2025-05-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_destinatoins_options_destinatoins_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatoins',
            name='slug',
        ),
    ]
