# Generated by Django 4.2.21 on 2025-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_destinatoins_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatoins',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
