# Generated by Django 4.2.21 on 2025-05-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_destinatoins_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinatoins',
            new_name='Destinations',
        ),
    ]
