# Generated by Django 4.2.21 on 2025-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_apropos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
