# Generated by Django 4.2.21 on 2025-05-15 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_destinatoins_destinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='destinations/gallery/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.destinations')),
            ],
        ),
    ]
