# Generated by Django 4.2.21 on 2025-05-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_messagecontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagecontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
