# Generated by Django 4.2.21 on 2025-05-16 22:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_messagecontact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseilvoyage',
            name='contenu',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='culture',
            name='titre',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
