# Generated by Django 4.2.21 on 2025-05-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_conseilvoyage_contenu_alter_culture_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseilvoyage',
            name='contenu',
            field=models.TextField(),
        ),
    ]
