# Generated by Django 4.2.21 on 2025-05-17 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_culture_slug_alter_culture_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='culture_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.culture')),
            ],
        ),
    ]
